#' @include tag-registry.R
#' @import stringr
NULL

register_tags(
  param = parse.name.description,
  quickcheck = parse.code
)

#' Roclet: make quickcheck tests.
#'
#' This roclet generates R files in the /tests directory that can make use of 
#' the \pkg{quickcheck} packages.
#'
#' @family roclets
#' @seealso \code{vignette("quickcheck", package = "roxygen2")}
#' @export
quickcheck_roclet <- function() {
  new_roclet(list(), "quickcheck_roclet")
}

#' @export
roc_process.quickcheck_roclet <- function(roclet, parsed, base_path, options = list()) {
  # Look at all blocks with roxygen comments
  blocks <- Filter(function(x) length(x) > 1, parsed$blocks)

  topics <- list()
  for (block in blocks) {
    new <- block_to_test(block, base_path, parsed$env)
    if (is.null(new)) next
    topics[[new$filename]] <- new$quickcheck
  }
  
  topics
}

block_to_test <- function(block, base_path, env) {
  # Must start by processing templates
  block <- process_templates(block, base_path)

  key_tags <- c("param", "quickcheck")
  if (!all(key_tags %in% names(block))) {
    return()
  }
  
  # Determine name
  name <- block$name %||% default_topic_name(block$object) %||%
      stop("Missing name at ", srcref_location(block$srcref), call. = FALSE)
  describe_in <- process_describe_in(block, env)
  filename <- paste0(describe_in$rdname %||% block$rdname %||%
          nice_name(name), ".R")
  
  quickcheck_file <- paste(
      "# Generated by roxygen2: do not edit by hand", 
      "library(quickcheck)",
      "test(",
      "forall(",
      paste0(
          paste(
              lapply(
                  block[names(block) == "param"], 
                  function(x) {
                    paste(
                        x$name, 
                        paste0("r", stringr::str_split(x$description, " ")[[1]][[1]], "()"), 
                        sep = " = ")}), 
              collapse = ",\n"), ","), 
      paste0(block$quickcheck, "),"),
      paste0("about = \"", name, "\")"), sep = "\n")
  
  list(quickcheck = quickcheck_file, filename = filename)
}

#' @export
roc_output.quickcheck_roclet <- function(roclet, results, base_path, options = list(),
                           check = TRUE) {
  tests <- normalizePath(file.path(base_path, "tests"))

  contents <- unlist(results, use.names = FALSE)

  paths <- file.path(tests, names(results))
  mapply(write_if_different, paths, contents, MoreArgs = list(check = check))

  if (check) {
    # Automatically delete any files in man directory that were generated
    # by roxygen in the past, but weren't generated in this sweep.

    old_paths <- setdiff(dir(tests, full.names = TRUE), paths)
    old_paths <- old_paths[!file.info(old_paths)$isdir]
    old_roxygen <- Filter(made_by_roxygen, old_paths)
    if (length(old_roxygen) > 0) {
      cat(paste0("Deleting ", basename(old_roxygen), collapse = "\n"), "\n", sep = "")
      unlink(old_roxygen)
    }
  }

  paths
}

#' @export
clean.quickcheck_roclet <- function(roclet, base_path) {
  qc <- dir(file.path(base_path, "tests"), full.names = TRUE)
  qc <- qc[!file.info(rd)$isdir]
  made_by_me <- vapply(qc, made_by_roxygen, logical(1))

  unlink(qc[made_by_me])
}
